In [2]:
import pandas as pd

In [3]:
# load the data from the CSV file datatypes are defined for the columns that had errors
data = pd.read_csv(
    "./data/match_data.csv",
    dtype={
        89: str,
        97: str,
        98: str,
    },
    parse_dates=[91],
)
data.head()

,Club ID,Club Name,Competition Name,Match ID,Period Number,Period Type,Assists,Assists Defensive,Assists Turnover Ratio,Bench Points,...,Basketball Matches - Match → Home Name,Basketball Matches - Match → Away Name,Basketball Matches - Match → Home ID,Basketball Matches - Match → Away ID,Basketball Matches - Match → Home Score,Basketball Matches - Match → Away Score,Basketball Matches - Match → Include In Conf Stats,Basketball Matches - Match → Include In Standings,Basketball Matches - Match → Place If Won,Basketball Matches - Match → Place If Lost
0,17257.0,Drake,2018-19 Men's Basketball,1007583,0,REGULAR,16,0,1.45,48,...,Drake,Buena Vista,103544.0,103383.0,98.0,52.0,0.0,0.0,0.0,0.0
1,17096.0,Buena Vista,2018-19 Men's Basketball,1007583,0,REGULAR,10,0,0.67,31,...,Drake,Buena Vista,103544.0,103383.0,98.0,52.0,0.0,0.0,0.0,0.0
2,18243.0,Col. of Idaho,2018-19 Men's Basketball,1007743,0,REGULAR,15,0,0.83,33,...,Utah,Col. of Idaho,104389.0,106093.0,96.0,76.0,0.0,0.0,0.0,0.0
3,18096.0,Utah,2018-19 Men's Basketball,1007743,0,REGULAR,22,0,2.44,38,...,Utah,Col. of Idaho,104389.0,106093.0,96.0,76.0,0.0,0.0,0.0,0.0
4,17296.0,Emory,2018-19 Men's Basketball,1007998,0,REGULAR,3,0,0.75,15,...,North Georgia,Emory,104002.0,103583.0,88.0,92.0,0.0,0.0,0.0,0.0

In [4]:
# show the info and description of the data
data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 634523 entries, 0 to 634522
Columns: 107 entries, Club ID to Basketball Matches - Match → Place If Lost
dtypes: datetime64[ns](1), float64(34), int64(63), object(9)
memory usage: 518.0+ MB

,Club ID,Match ID,Period Number,Assists,Assists Defensive,Assists Turnover Ratio,Bench Points,Biggest Lead,Biggest Scoring Run,Blocks,...,Basketball Matches - Match → Tournament ID,Basketball Matches - Match → Full Time Played,Basketball Matches - Match → Home ID,Basketball Matches - Match → Away ID,Basketball Matches - Match → Home Score,Basketball Matches - Match → Away Score,Basketball Matches - Match → Include In Conf Stats,Basketball Matches - Match → Include In Standings,Basketball Matches - Match → Place If Won,Basketball Matches - Match → Place If Lost
count,634512.000000,6.345230e+05,634523.0,634523.000000,634523.0,634523.000000,634523.000000,634523.000000,634523.000000,634523.000000,...,474448.000000,0.0,467462.000000,467462.000000,457398.000000,457398.000000,467462.000000,467462.000000,474448.0,474448.0
mean,17656.475999,2.184290e+06,0.0,13.360655,0.0,1.209540,20.065881,11.160974,7.880121,3.113649,...,93.234491,NaN,104330.157758,104334.550304,75.596732,72.163542,0.909054,0.997912,0.0,0.0
min,16970.000000,1.007557e+06,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,NaN,103257.000000,103257.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
25%,17283.000000,2.333619e+06,0.0,10.000000,0.0,0.750000,12.000000,4.000000,6.000000,2.000000,...,0.000000,NaN,103573.000000,103567.000000,67.000000,64.000000,1.000000,1.000000,0.0,0.0
50%,17605.000000,2.343048e+06,0.0,13.000000,0.0,1.062500,19.000000,9.000000,8.000000,3.000000,...,0.000000,NaN,103899.000000,103896.000000,75.000000,72.000000,1.000000,1.000000,0.0,0.0
75%,17932.000000,2.345900e+06,0.0,16.000000,0.0,1.500000,26.000000,16.000000,10.000000,4.000000,...,0.000000,NaN,104227.000000,104224.000000,83.000000,80.000000,1.000000,1.000000,0.0,0.0
max,30008.000000,2.426940e+06,0.0,59.000000,0.0,29.000000,129.000000,108.000000,41.000000,21.000000,...,2153.000000,NaN,166612.000000,168204.000000,166.000000,132.000000,1.000000,1.000000,0.0,0.0
std,779.229158,3.630388e+05,0.0,4.777088,0.0,0.725535,11.220659,9.885009,4.166151,2.135235,...,428.338988,NaN,4432.737640,4382.989545,13.063331,12.499325,0.287533,0.045646,0.0,0.0

In [5]:
# drop all the columns that are not useful
data = data.drop("Club ID", axis=1)
data = data.drop("Club Name", axis=1)
data = data.drop("Competition Name", axis=1)
data = data.drop("Period Number", axis=1)
data = data.drop("Period Type", axis=1)
data = data.drop("Assists Defensive", axis=1)
data = data.drop("Biggest Lead Score", axis=1)
data = data.drop("Biggest Scoring Run Score", axis=1)
data = data.drop("Efficiency Custom", axis=1)
data = data.drop("Fouls Coach Disqualifying", axis=1)
data = data.drop("Fouls Technical Other", axis=1)
data = data.drop("Fouls Throw In", axis=1)
data = data.drop("Fouls Unsportsmanlike", axis=1)
data = data.drop("Head Coach Challenge Accepted", axis=1)
data = data.drop("Head Coach Challenge Rejected", axis=1)
data = data.drop("Basketball Matches - Match → Status", axis=1)
data = data.drop("Basketball Matches - Match → Extra Periods Used", axis=1)
data = data.drop("Basketball Matches - Match → Match Time Utc", axis=1)
data = data.drop("Basketball Matches - Match → Attendance", axis=1)
data = data.drop("Basketball Matches - Match → Weather", axis=1)
data = data.drop("Basketball Matches - Match → Is Conference", axis=1)
data = data.drop("Basketball Matches - Match → Tournament ID", axis=1)
data = data.drop("Basketball Matches - Match → Full Time Played", axis=1)
data = data.drop("Basketball Matches - Match → Home Name", axis=1)
data = data.drop("Basketball Matches - Match → Away Name", axis=1)
data = data.drop("Basketball Matches - Match → Home ID", axis=1)
data = data.drop("Basketball Matches - Match → Away ID", axis=1)
data = data.drop("Basketball Matches - Match → Home Score", axis=1)
data = data.drop("Basketball Matches - Match → Away Score", axis=1)
data = data.drop("Basketball Matches - Match → Include In Conf Stats", axis=1)
data = data.drop("Basketball Matches - Match → Include In Standings", axis=1)
data = data.drop("Basketball Matches - Match → Place If Won", axis=1)
data = data.drop("Basketball Matches - Match → Place If Lost", axis=1)
data.drop_duplicates(inplace=True)

In [6]:
# group the data by match id and make sure there are only 2 teams per match
data.sort_values(by=["Match ID", "Points"], inplace=True, ascending=[True, False])
match_counts = data["Match ID"].value_counts()
valid_match_ids = match_counts[match_counts == 2].index
data = data[data["Match ID"].isin(valid_match_ids)]

In [7]:
# create a new column that indicates if the team won the match
data["Win"] = data["Points"] > data["Points Against"]
data["Win"] = data["Win"].astype(int)

In [8]:
# show the info for the data
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 177732 entries, 228 to 513256
Data columns (total 75 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Match ID                         177732 non-null  int64
 1   Assists                          177732 non-null  int64
 2   Assists Turnover Ratio           177732 non-null  float64
 3   Bench Points                     177732 non-null  int64
 4   Biggest Lead                     177732 non-null  int64
 5   Biggest Scoring Run              177732 non-null  int64
 6   Blocks                           177732 non-null  int64
 7   Blocks Received                  177732 non-null  int64
 8   Defensive Points Per Possession  177732 non-null  float64
 9   Defensive Rating                 177732 non-null  float64
 10  Efficiency                       177732 non-null  int64
 11  Fast Break Points Attempted      177732 non-null  int64
 12  Fast Break Points Made           177732 non-null  int64
 13  Fast Break Points Percentage     177732 non-null  float64
 14  Field Goals Attempted            177732 non-null  int64
 15  Field Goals Effective Adjusted   177732 non-null  float64
 16  Field Goals Made                 177732 non-null  int64
 17  Field Goals Percentage           177732 non-null  float64
 18  Fouled Out                       177732 non-null  int64
 19  Fouls Bench Technical            177732 non-null  int64
 20  Fouls Coach Technical            177732 non-null  int64
 21  Fouls Disqualifying              177732 non-null  int64
 22  Fouls Offensive                  177732 non-null  int64
 23  Fouls On                         177732 non-null  int64
 24  Fouls Personal                   177732 non-null  int64
 25  Fouls Team                       177732 non-null  int64
 26  Fouls Technical                  177732 non-null  int64
 27  Fouls Total                      177732 non-null  int64
 28  Free Throws Attempted            177732 non-null  int64
 29  Free Throws Made                 177732 non-null  int64
 30  Free Throws Percentage           177732 non-null  float64
 31  Lead Changes                     177732 non-null  int64
 32  Minutes                          177732 non-null  float64
 33  Offensive Points Per Possession  177732 non-null  float64
 34  Offensive Rating                 177732 non-null  float64
 35  Pace                             177732 non-null  int64
 36  Points                           177732 non-null  int64
 37  Points Against                   177732 non-null  int64
 38  Points Fast Break                177732 non-null  int64
 39  Points From Turnovers            177732 non-null  int64
 40  Points In Paint                  177732 non-null  int64
 41  Points In Paint Attempted        177732 non-null  int64
 42  Points In Paint Made             177732 non-null  int64
 43  Points In Paint Percentage       177732 non-null  float64
 44  Points Second Chance             177732 non-null  int64
 45  Possessions                      177732 non-null  float64
 46  Possessions Opponent             177732 non-null  float64
 47  Rebounds Defensive               177732 non-null  int64
 48  Rebounds Defensive Deadball      177732 non-null  int64
 49  Rebounds Offensive               177732 non-null  int64
 50  Rebounds Offensive Deadball      177732 non-null  int64
 51  Rebounds Personal                177732 non-null  int64
 52  Rebounds Team                    177732 non-null  int64
 53  Rebounds Team Defensive          177732 non-null  int64
 54  Rebounds Team Offensive          177732 non-null  int64
 55  Rebounds Total                   177732 non-null  int64
 56  Second Chance Points Attempted   177732 non-null  int64
 57  Second Chance Points Made        177732 non-null  int64
 58  Second Chance Points Percentage  177732 non-null  float64
 59  Steals                           177732 non-null  int64
 60  Three Pointers Attempted         177732 non-null  int64
 61  Three Pointers Made              177732 non-null  int64
 62  Three Pointers Percentage        177732 non-null  float64
 63  Time Leading                     177732 non-null  float64
 64  Times Scores Level               177732 non-null  int64
 65  Transition Defence               177732 non-null  float64
 66  Transition Offence               177732 non-null  float64
 67  Turnovers                        177732 non-null  int64
 68  Turnovers Team                   177732 non-null  int64
 69  Two Pointers Attempted           177732 non-null  int64
 70  Two Pointers Made                177732 non-null  int64
 71  Two Pointers Percentage          177732 non-null  float64
 72  Team ID                          177732 non-null  int64
 73  Team Name                        177732 non-null  object
 74  Win                              177732 non-null  int64
dtypes: float64(19), int64(55), object(1)
memory usage: 103.1+ MB

In [9]:
# save the cleaned data
data.to_csv("data/match_data_cleaned.csv", index=False)